;; Copyright (c) 2012, Alvaro Castro-Castilla. All rights reserved.

(pg:app
 setup: (lambda (resources)
          (make-environment 1280 800 resources #f))
 main-loop: (lambda (env)
             (let* ((graphics (environment-graphics env))
                    (surface (graphics-surface graphics))
                    (canvas (graphics-canvas graphics))
                    (maxx (environment-size-x env))
                    (maxy (environment-size-y env))
                    (box-size-x (/ (* maxx 2.5) 100))
                    (box-size-y (* maxy 20))
                    (box-1-pos-x (/ (* maxx 10) 100))
                    (box-2-pos-x (- maxx (/ (* maxx 10) 100))))
               (let loop ((box-1-pos-y (/ maxy 2))
                          (box-2-pos-y (/ maxy 2)))
                 (draw:fill-color! (make-color/rgba 1 1 1 1))
                 ;(draw:rectangle/corners 0 0 (+ 0  box-size-x) (+ 0 box-size-y))
                 ;(draw:rectangle/corners 0 0 10 10)
                 (draw:rectangle/center box-1-pos-x box-1-pos-y (/ box-size-x 10) (/ box-size-x 10))
                 ;(draw:rectangle/center box-2-pos-x box-2-pos-y box-size-x box-size-y)
                 (draw:on surface)
                 (loop box-1-pos-y box-2-pos-y)))))
